rabbitmq.exchange.name=clients
rabbitmq.create.client.key=client.created
rabbitmq.create.client.queue.name=client.created.queue
rabbitmq.delete.client.key=client.deleted
rabbitmq.delete.client.queue.name=client.deleted.queue
