rabbitmq.host=localhost
rabbitmq.port=5672

rabbitmq.username=root
rabbitmq.password=root

rabbitmq.exchange.name=clients
rabbitmq.create.client.key=client.created
rabbitmq.create.client.queue.name=client.created.queue