spring.application.name=RentService
rsa.private-key=classpath:certs/private.pem
rsa.public-key=classpath:certs/public.pem
logging.level.root=INFO
logging.level.pl.edu.dik.tks=DEBUG
logging.level.org.springframework.security=TRACE
logging.level.org.springframework.web=DEBUG
server.port=8080


spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672

spring.rabbitmq.username=root
spring.rabbitmq.password=root

# Retry i DLQ
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=5
spring.rabbitmq.listener.simple.retry.initial-interval=1000
spring.rabbitmq.listener.simple.retry.multiplier=2
spring.rabbitmq.listener.simple.retry.max-interval=10000
spring.rabbitmq.listener.simple.default-requeue-rejected=false
