rabbitmq.exchange.name=clients
rabbitmq.create.client.key=client.created
rabbitmq.create.client.queue.name=client.created.queue

rabbitmq.deadletter.exchange.name=dead.letter.exchange
rabbitmq.deadletter.queue.name=dead.letter.queue