<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:gm="http://viewsoap.adapters.soap/games" attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://viewsoap.adapters.soap/games" version="1.0">
        
  
  
  <xs:element name="createGameRequest" type="gm:createGameRequest"/>
        
  
  
  <xs:element name="deleteGameRequest" type="gm:deleteGameRequest"/>
        
  
  
  <xs:element name="gameResponse" type="gm:gameResponse"/>
        
  
  
  <xs:element name="getAllGamesRequest" type="gm:getAllGamesRequest"/>
        
  
  
  <xs:element name="getAllGamesResponse" type="gm:getAllGamesResponse"/>
        
  
  
  <xs:element name="getGameByIdRequest" type="gm:getGameByIdRequest"/>
        
  
  
  <xs:element name="updateGameRequest" type="gm:updateGameRequest"/>
        
  
  
  <xs:complexType name="createGameRequest">
                
    
    
    <xs:sequence>
                        
      
      
      <xs:element name="name" type="xs:string"/>
                        
      
      
      <xs:element name="pricePerDay" type="xs:int"/>
                        
      
      
      <xs:element name="minPlayers" type="xs:int"/>
                        
      
      
      <xs:element name="maxPlayers" type="xs:int"/>
                      
    
    
    </xs:sequence>
              
  
  
  </xs:complexType>
        
  
  
  <xs:complexType name="deleteGameRequest">
                
    
    
    <xs:sequence>
                        
      
      
      <xs:element name="id" type="xs:string"/>
                      
    
    
    </xs:sequence>
              
  
  
  </xs:complexType>
        
  
  
  <xs:complexType name="gameResponse">
                
    
    
    <xs:sequence>
                        
      
      
      <xs:element name="id" type="xs:string"/>
                        
      
      
      <xs:element name="name" type="xs:string"/>
                        
      
      
      <xs:element name="pricePerDay" type="xs:int"/>
                        
      
      
      <xs:element name="minPlayers" type="xs:int"/>
                        
      
      
      <xs:element name="maxPlayers" type="xs:int"/>
                        
      
      
      <xs:element name="rentalStatusCount" type="xs:int"/>
                      
    
    
    </xs:sequence>
              
  
  
  </xs:complexType>
        
  
  
  <xs:complexType name="getAllGamesRequest">
                
    
    
    <xs:sequence/>
              
  
  
  </xs:complexType>
        
  
  
  <xs:complexType name="getAllGamesResponse">
                
    
    
    <xs:sequence>
                        
      
      
      <xs:element maxOccurs="unbounded" minOccurs="0" name="games" type="gm:gameResponse"/>
                      
    
    
    </xs:sequence>
              
  
  
  </xs:complexType>
        
  
  
  <xs:complexType name="getGameByIdRequest">
                
    
    
    <xs:sequence>
                        
      
      
      <xs:element name="id" type="xs:string"/>
                      
    
    
    </xs:sequence>
              
  
  
  </xs:complexType>
        
  
  
  <xs:complexType name="updateGameRequest">
                
    
    
    <xs:sequence>
                        
      
      
      <xs:element name="id" type="xs:string"/>
                        
      
      
      <xs:element name="name" type="xs:string"/>
                        
      
      
      <xs:element name="pricePerDay" type="xs:int"/>
                      
    
    
    </xs:sequence>
              
  
  
  </xs:complexType>
      


</xs:schema>
